{
 "title": "4 Golden Signals Dashboard",
 "description": "Dashboard focusing on the 4 Golden Signals: Latency, Requests, Errors, and Saturation.",
 "tags": [ "nginx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (Request Duration Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"my-release-ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"my-release-ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "P90 Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"my-release-ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "P50 Latency"
    }
   ]
  },
  {
   "title": "Requests (Request Volume)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"my-release-ingress\"}[2m]))",
     "legendFormat": "Request Volume"
    }
   ]
  },
  {
   "title": "Errors (Success Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=\"sre-cource-student-2\", ingress=\"sre-cource-api\", status!~\"[4-5].*\"}[15s])) / sum(rate(nginx_ingress_controller_requests{namespace=\"sre-cource-student-2\", ingress=\"sre-cource-api\"}[15s]))",
     "legendFormat": "Sucsess Rate"
    }
   ]
  },
  {
   "title": "Saturation (CPU Utilization)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total[1m])) by (pod)",
     "legendFormat": "CPU Utilization"
    }
   ]
  }
 ]
}