# my global config)
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
            - targets: ['localhost:9093']
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
  
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.18:9100', '192.168.1.19:9100', '192.168.1.20:9100', '192.168.1.21:9100', '192.168.1.22:9100', '192.168.1.3:9100']
  
  - job_name: 'etcd'
    static_configs:
      - targets: ['192.168.1.19:2379', '192.168.1.20:2379', '192.168.1.21:2379']

  - job_name: 'postgress-exporter'
    static_configs:
      - targets: ['192.168.1.18:9187', '192.168.1.22:9187']
  
  - job_name: 'patroni'
    static_configs:
      - targets: ['192.168.1.18:8008', '192.168.1.22:8008']

  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['192.168.1.3:9115']


  - job_name: blackbox
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
          - "https://176.109.82.213/swagger/index.html"
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - target_label: __address__
          replacement: "192.168.1.3:9115"
        - source_labels: [__meta_dns_name]
          target_label: __param_hostname
        - source_labels: [__meta_dns_name]
          target_label: vhost