apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-cource-api.fullname" . }}
  labels:
    {{- include "sre-cource-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP

  selector:
    {{- include "sre-cource-api.selectorLabels" . | nindent 4 }}
